// THIS FILE IS OVERWRITTEN AND POPULATED BY THE CLOUDFORMATION 
// SCRIPT.  ONLY USE FOR DEV/TEST OUTSIDE OF CLOUDFORMATION 
// DEPLOYMENT
export default function NetworkConstants() { return {
"NetworkId":"n-XXXX",
"MemberId":"m-XXXX"
}};